"""add constraints tables

Revision ID: 0d633dc08f98
Revises: e47081302c4e
Create Date: 2026-03-22 17:32:07.198656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d633dc08f98'
down_revision: Union[str, Sequence[str], None] = 'e47081302c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hard_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('constraint_type', sa.Enum('NO_TEACHER_DOUBLE_BOOK', 'NO_ROOM_DOUBLE_BOOK', 'NO_GROUP_DOUBLE_BOOK', 'ROOM_CAPACITY_SUFFICIENT', 'ROOM_TYPE_MATCH', 'RESPECT_TEACHER_UNAVAILABILITY', 'RESPECT_ROOM_BLACKOUT', 'CONTIGUOUS_LAB_SLOTS', 'EXAM_DATE_SEPARATION', 'TEACHER_PREFERS_MORNING', 'AVOID_CONSECUTIVE_SAME_SUBJECT', 'MINIMIZE_STUDENT_FREE_SLOTS', 'MINIMIZE_TEACHER_FREE_SLOTS', 'DISTRIBUTE_SUBJECTS_EVENLY', 'BALANCE_TEACHER_LOAD', name='constrainttype'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['timetable_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soft_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('constraint_type', sa.Enum('NO_TEACHER_DOUBLE_BOOK', 'NO_ROOM_DOUBLE_BOOK', 'NO_GROUP_DOUBLE_BOOK', 'ROOM_CAPACITY_SUFFICIENT', 'ROOM_TYPE_MATCH', 'RESPECT_TEACHER_UNAVAILABILITY', 'RESPECT_ROOM_BLACKOUT', 'CONTIGUOUS_LAB_SLOTS', 'EXAM_DATE_SEPARATION', 'TEACHER_PREFERS_MORNING', 'AVOID_CONSECUTIVE_SAME_SUBJECT', 'MINIMIZE_STUDENT_FREE_SLOTS', 'MINIMIZE_TEACHER_FREE_SLOTS', 'DISTRIBUTE_SUBJECTS_EVENLY', 'BALANCE_TEACHER_LOAD', name='constrainttype'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('weight', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['timetable_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soft_constraints')
    op.drop_table('hard_constraints')
    # ### end Alembic commands ###
