"""add generation and history tables

Revision ID: 0f8db8a263c5
Revises: 0d633dc08f98
Create Date: 2026-03-22 17:38:14.267405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8db8a263c5'
down_revision: Union[str, Sequence[str], None] = '0d633dc08f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_instance_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('archived_by', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.Column('archive_reason', sa.Enum('YEAR_RESET', 'SEMESTER_END', 'MANUAL', 'SUPERSEDED', name='archivereason'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_reset_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reset_type', sa.Enum('FULL_YEAR', 'SEMESTER', 'PROFILE_SPECIFIC', name='resettype'), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('profiles_reset', sa.JSON(), nullable=True),
    sa.Column('reset_by', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reset_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('combination_id', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('timetable_type', sa.Enum('CLASS', 'FACULTY', 'ROOM', 'EVENT', 'EXAM', 'IP', 'CUSTOM', name='timetabletype'), nullable=False),
    sa.Column('generation_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='generationstatus'), nullable=False),
    sa.Column('algorithm_used', sa.Enum('GREEDY', 'OR_TOOLS', name='algorithmtype'), nullable=False),
    sa.Column('instances_requested', sa.Integer(), nullable=False),
    sa.Column('instances_produced', sa.Integer(), nullable=False),
    sa.Column('score_best_instance', sa.Float(), nullable=True),
    sa.Column('run_duration_ms', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['combination_id'], ['profile_combinations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['timetable_profiles.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('instance_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('soft_score', sa.Float(), nullable=True),
    sa.Column('hard_violations', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SELECTED', 'PUBLISHED', 'ARCHIVED', name='instancestatus'), nullable=False),
    sa.Column('selected_by', sa.Integer(), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['timetable_generations.id'], ),
    sa.ForeignKeyConstraint(['selected_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('student_group_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.Enum('LECTURE', 'LAB', 'TUTORIAL', 'SEMINAR', 'EVENT', 'EXAM', 'IP', 'FREE', name='sessiontype'), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(length=300), nullable=True),
    sa.Column('external_speaker', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['timetable_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['student_group_id'], ['student_groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable_slots')
    op.drop_table('timetable_instances')
    op.drop_table('timetable_generations')
    op.drop_table('timetable_reset_log')
    op.drop_table('timetable_history')
    # ### end Alembic commands ###
