"""add profiles tables

Revision ID: e47081302c4e
Revises: aeaadc4f2374
Create Date: 2026-03-22 17:28:35.459321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47081302c4e'
down_revision: Union[str, Sequence[str], None] = 'aeaadc4f2374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profile_combinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_type', sa.Enum('DEPARTMENT', 'YEAR', 'DIVISION', 'EVENT', 'EXAM', 'CUSTOM', name='scopetype'), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_combination_members',
    sa.Column('combination_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['combination_id'], ['profile_combinations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['timetable_profiles.id'], ),
    sa.PrimaryKeyConstraint('combination_id', 'profile_id')
    )
    op.create_table('profile_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('param_key', sa.String(length=100), nullable=False),
    sa.Column('param_value', sa.Text(), nullable=False),
    sa.Column('param_type', sa.Enum('INT', 'FLOAT', 'STRING', 'BOOLEAN', 'TIME', 'JSON', name='paramtype'), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['timetable_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'param_key', name='uq_profile_param')
    )
    op.create_table('profile_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('ROOM', 'FACULTY', 'STUDENT_GROUP', 'SUBJECT', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['timetable_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_resources')
    op.drop_table('profile_parameters')
    op.drop_table('profile_combination_members')
    op.drop_table('timetable_profiles')
    op.drop_table('profile_combinations')
    op.drop_table('admins')
    # ### end Alembic commands ###
